openapi: 3.0.3
info:
  title: Flipdish API - Apps Accounts StripeCustomConnect API
  version: v1.0
  description: Flipdish Open API v1.0 — Apps operations. Flipdish is an online ordering and branded-app platform for restaurants and takeaways. This specification was derived from the official Flipdish Swagger document and grouped by resource domain.
  contact:
    name: Flipdish Support
    email: help@flipdish.com
    url: https://help.flipdish.com
  x-generated-from: https://api.flipdish.co/swagger/docs/v1.0
  x-last-validated: '2026-06-02'
servers:
- url: https://api.flipdish.co
  description: Flipdish production API
security:
- oauth2:
  - api
tags:
- name: StripeCustomConnect
  description: Operations for Stripe Custom Connect.
paths:
  /api/v1.0/{appId}/customconnect/{storeId}:
    get:
      tags:
      - StripeCustomConnect
      operationId: GetCustomConnect
      parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: integer
          format: int32
        description: The store id path parameter.
        example: 500123
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiArrayResult_StripeCustomConnectedAccount_'
              examples:
                GetCustomConnect200Example:
                  summary: Default GetCustomConnect 200 response
                  x-microcks-default: true
                  value:
                    Data: []
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetCustomConnect400Example:
                  summary: Default GetCustomConnect 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetCustomConnect401Example:
                  summary: Default GetCustomConnect 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetCustomConnect403Example:
                  summary: Default GetCustomConnect 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetCustomConnect500Example:
                  summary: Default GetCustomConnect 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Get Custom Connect
      description: Get Custom Connect via the Flipdish Open API v1.0 (GET /api/v1.0/{appId}/customconnect/{storeId}).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/refresh-link:
    get:
      tags:
      - StripeCustomConnect
      operationId: StripeCustomConnect_Refresh
      parameters:
      - name: linkRequestId
        in: query
        required: true
        schema:
          type: integer
          format: int32
        description: The link request id query parameter.
        example: 500123
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                StripeCustomConnect_Refresh200Example:
                  summary: Default StripeCustomConnect_Refresh 200 response
                  x-microcks-default: true
                  value: {}
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                StripeCustomConnect_Refresh400Example:
                  summary: Default StripeCustomConnect_Refresh 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                StripeCustomConnect_Refresh401Example:
                  summary: Default StripeCustomConnect_Refresh 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                StripeCustomConnect_Refresh403Example:
                  summary: Default StripeCustomConnect_Refresh 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                StripeCustomConnect_Refresh500Example:
                  summary: Default StripeCustomConnect_Refresh 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Stripe Custom Connect_Refresh
      description: Stripe Custom Connect_Refresh via the Flipdish Open API v1.0 (GET /api/v1.0/{appId}/customconnect/refresh-link).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/verification-status:
    get:
      tags:
      - StripeCustomConnect
      operationId: GetVerificationStatus
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      - name: stripeConnectedAccountId
        in: query
        required: true
        schema:
          type: string
        description: The stripe connected account id query parameter.
        example: '500123'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_StripeConnectedAccount_'
              examples:
                GetVerificationStatus200Example:
                  summary: Default GetVerificationStatus 200 response
                  x-microcks-default: true
                  value:
                    Data:
                      FlipdishConnectedAccountId: 500123
                      StripeId: '500123'
                      WhitelabelConfigId: 500123
                      CardPaymentsStatus: Inactive
                      TransfersStatus: Inactive
                      AccountStatus: Disabled
                      PayoutsEnabled: true
                      PaymentsEnabled: true
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetVerificationStatus400Example:
                  summary: Default GetVerificationStatus 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetVerificationStatus401Example:
                  summary: Default GetVerificationStatus 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetVerificationStatus403Example:
                  summary: Default GetVerificationStatus 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                GetVerificationStatus500Example:
                  summary: Default GetVerificationStatus 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Get Verification Status
      description: Get Verification Status via the Flipdish Open API v1.0 (GET /api/v1.0/{appId}/customconnect/verification-status).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/bank-account:
    post:
      tags:
      - StripeCustomConnect
      operationId: CreateBankAccountAndConnectedAccount
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      requestBody:
        required: false
        content: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_BankAccountDetail_'
              examples:
                CreateBankAccountAndConnectedAccount200Example:
                  summary: Default CreateBankAccountAndConnectedAccount 200 response
                  x-microcks-default: true
                  value:
                    Data:
                      Id: 500123
                      StoreNames:
                      - Example Name
                      AccountState: Unverified
                      StripeConnectedAccountInfo:
                        AccountStatus: Disabled
                        StripeId: '500123'
                        CardPaymentStatus: Inactive
                        PayoutScheduleInterval: Manual
                        PayoutsEnabled: true
                        PayoutsPaused: true
                        PaymentsEnabled: true
                      BankAddress: string
                      BankCountryCode: IE
                      AccountHolderAddress: string
                      AccountHolderCountryCode: IE
                      VatNumber: string
                      CurrencyCode: EUR
                      StoreIds:
                      - 1
                      BankName: Example Name
                      AccountName: Example Name
                      Iban: string
                      Swift: string
                      NationalClearingCode: string
                      PopulatedAccountFields: []
                      RejectionReason: string
                      BusinessType: Individual
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateBankAccountAndConnectedAccount400Example:
                  summary: Default CreateBankAccountAndConnectedAccount 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateBankAccountAndConnectedAccount401Example:
                  summary: Default CreateBankAccountAndConnectedAccount 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateBankAccountAndConnectedAccount403Example:
                  summary: Default CreateBankAccountAndConnectedAccount 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateBankAccountAndConnectedAccount500Example:
                  summary: Default CreateBankAccountAndConnectedAccount 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Create Bank Account and Connected Account
      description: Create Bank Account and Connected Account via the Flipdish Open API v1.0 (POST /api/v1.0/{appId}/customconnect/bank-account).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/{bankAccountId}/create-update-account:
    post:
      tags:
      - StripeCustomConnect
      operationId: CreateStripeConnectedAccount
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      - name: bankAccountId
        in: path
        required: true
        schema:
          type: integer
          format: int32
        description: The bank account id path parameter.
        example: 500123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_StripeConnectedAccount_'
              examples:
                CreateStripeConnectedAccount200Example:
                  summary: Default CreateStripeConnectedAccount 200 response
                  x-microcks-default: true
                  value:
                    Data:
                      FlipdishConnectedAccountId: 500123
                      StripeId: '500123'
                      WhitelabelConfigId: 500123
                      CardPaymentsStatus: Inactive
                      TransfersStatus: Inactive
                      AccountStatus: Disabled
                      PayoutsEnabled: true
                      PaymentsEnabled: true
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccount400Example:
                  summary: Default CreateStripeConnectedAccount 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccount401Example:
                  summary: Default CreateStripeConnectedAccount 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccount403Example:
                  summary: Default CreateStripeConnectedAccount 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccount500Example:
                  summary: Default CreateStripeConnectedAccount 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Create Stripe Connected Account
      description: Create Stripe Connected Account via the Flipdish Open API v1.0 (POST /api/v1.0/{appId}/customconnect/{bankAccountId}/create-update-account).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/bank-account/{bankAccountId}/businesstype:
    post:
      tags:
      - StripeCustomConnect
      operationId: SetBankAccountBusinessType
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      - name: bankAccountId
        in: path
        required: true
        schema:
          type: integer
          format: int32
        description: The bank account id path parameter.
        example: 500123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              enum:
              - Individual
              - Company
              - NonProfit
              - GovernmentEntity
              type: string
            examples:
              SetBankAccountBusinessTypeRequestExample:
                summary: Default SetBankAccountBusinessType request
                x-microcks-default: true
                value: Individual
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_BankAccountDetail_'
              examples:
                SetBankAccountBusinessType200Example:
                  summary: Default SetBankAccountBusinessType 200 response
                  x-microcks-default: true
                  value:
                    Data:
                      Id: 500123
                      StoreNames:
                      - Example Name
                      AccountState: Unverified
                      StripeConnectedAccountInfo:
                        AccountStatus: Disabled
                        StripeId: '500123'
                        CardPaymentStatus: Inactive
                        PayoutScheduleInterval: Manual
                        PayoutsEnabled: true
                        PayoutsPaused: true
                        PaymentsEnabled: true
                      BankAddress: string
                      BankCountryCode: IE
                      AccountHolderAddress: string
                      AccountHolderCountryCode: IE
                      VatNumber: string
                      CurrencyCode: EUR
                      StoreIds:
                      - 1
                      BankName: Example Name
                      AccountName: Example Name
                      Iban: string
                      Swift: string
                      NationalClearingCode: string
                      PopulatedAccountFields: []
                      RejectionReason: string
                      BusinessType: Individual
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                SetBankAccountBusinessType400Example:
                  summary: Default SetBankAccountBusinessType 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                SetBankAccountBusinessType401Example:
                  summary: Default SetBankAccountBusinessType 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                SetBankAccountBusinessType403Example:
                  summary: Default SetBankAccountBusinessType 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                SetBankAccountBusinessType500Example:
                  summary: Default SetBankAccountBusinessType 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Set Bank Account Business Type
      description: Set Bank Account Business Type via the Flipdish Open API v1.0 (POST /api/v1.0/{appId}/customconnect/bank-account/{bankAccountId}/businesstype).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/{bankAccountId}/update-bank-account-details:
    post:
      tags:
      - StripeCustomConnect
      operationId: UpdateBankAccountDetails
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      - name: bankAccountId
        in: path
        required: true
        schema:
          type: integer
          format: int32
        description: The bank account id path parameter.
        example: 500123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccountDetailsUpdateRequest'
            examples:
              UpdateBankAccountDetailsRequestExample:
                summary: Default UpdateBankAccountDetails request
                x-microcks-default: true
                value:
                  BankAddress: string
                  AccountHolderAddress: string
                  VatNumber: string
                  StoreIds:
                  - 1
                  BankName: Example Name
                  AccountName: Example Name
                  Iban: string
                  Swift: string
                  NationalClearingCode: string
                  PopulatedAccountFields: []
                  RejectionReason: string
                  BusinessType: Individual
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_StripeConnectedAccount_'
              examples:
                UpdateBankAccountDetails200Example:
                  summary: Default UpdateBankAccountDetails 200 response
                  x-microcks-default: true
                  value:
                    Data:
                      FlipdishConnectedAccountId: 500123
                      StripeId: '500123'
                      WhitelabelConfigId: 500123
                      CardPaymentsStatus: Inactive
                      TransfersStatus: Inactive
                      AccountStatus: Disabled
                      PayoutsEnabled: true
                      PaymentsEnabled: true
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdateBankAccountDetails400Example:
                  summary: Default UpdateBankAccountDetails 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdateBankAccountDetails401Example:
                  summary: Default UpdateBankAccountDetails 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdateBankAccountDetails403Example:
                  summary: Default UpdateBankAccountDetails 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdateBankAccountDetails500Example:
                  summary: Default UpdateBankAccountDetails 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Update Bank Account Details
      description: Update Bank Account Details via the Flipdish Open API v1.0 (POST /api/v1.0/{appId}/customconnect/{bankAccountId}/update-bank-account-details).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/{stripeConnectedAccountId}/create-account-link:
    post:
      tags:
      - StripeCustomConnect
      operationId: CreateStripeConnectedAccountLink
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      - name: stripeConnectedAccountId
        in: path
        required: true
        schema:
          type: string
        description: The stripe connected account id path parameter.
        example: '500123'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeAccountLinkRequest'
            examples:
              CreateStripeConnectedAccountLinkRequestExample:
                summary: Default CreateStripeConnectedAccountLink request
                x-microcks-default: true
                value:
                  StripeId: '500123'
                  ReturnUrl: https://api.flipdish.co/example
                  Collect: CurrentlyDue
                  Type: Onboarding
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_StripeConnectedAccount_'
              examples:
                CreateStripeConnectedAccountLink200Example:
                  summary: Default CreateStripeConnectedAccountLink 200 response
                  x-microcks-default: true
                  value:
                    Data:
                      FlipdishConnectedAccountId: 500123
                      StripeId: '500123'
                      WhitelabelConfigId: 500123
                      CardPaymentsStatus: Inactive
                      TransfersStatus: Inactive
                      AccountStatus: Disabled
                      PayoutsEnabled: true
                      PaymentsEnabled: true
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccountLink400Example:
                  summary: Default CreateStripeConnectedAccountLink 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccountLink401Example:
                  summary: Default CreateStripeConnectedAccountLink 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccountLink403Example:
                  summary: Default CreateStripeConnectedAccountLink 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                CreateStripeConnectedAccountLink500Example:
                  summary: Default CreateStripeConnectedAccountLink 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Create Stripe Connected Account Link
      description: Create Stripe Connected Account Link via the Flipdish Open API v1.0 (POST /api/v1.0/{appId}/customconnect/{stripeConnectedAccountId}/create-account-link).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v1.0/{appId}/customconnect/update-payout-schedule/{stripeConnectedAccountId}/{interval}:
    post:
      tags:
      - StripeCustomConnect
      operationId: UpdatePayoutSchedule
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
        description: The app id path parameter.
        example: '500123'
      - name: stripeConnectedAccountId
        in: path
        required: true
        schema:
          type: string
        description: The stripe connected account id path parameter.
        example: '500123'
      - name: interval
        in: path
        required: true
        schema:
          type: string
        description: The interval path parameter.
        example: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestApiResult_ModelBase_'
              examples:
                UpdatePayoutSchedule200Example:
                  summary: Default UpdatePayoutSchedule 200 response
                  x-microcks-default: true
                  value:
                    Data: {}
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdatePayoutSchedule400Example:
                  summary: Default UpdatePayoutSchedule 400 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '401':
          description: Authentication has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdatePayoutSchedule401Example:
                  summary: Default UpdatePayoutSchedule 401 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '403':
          description: Successful authentication, but authorization has been denied for this request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdatePayoutSchedule403Example:
                  summary: Default UpdatePayoutSchedule 403 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlipdishError'
              examples:
                UpdatePayoutSchedule500Example:
                  summary: Default UpdatePayoutSchedule 500 response
                  x-microcks-default: true
                  value:
                    error:
                      errorMessage: Invalid or missing parameters.
                      errorCode: BadRequest
                      details: Validation failed for field 'storeId'.
      security:
      - oauth2:
        - api
      summary: Flipdish Update Payout Schedule
      description: Update Payout Schedule via the Flipdish Open API v1.0 (POST /api/v1.0/{appId}/customconnect/update-payout-schedule/{stripeConnectedAccountId}/{interval}).
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    StripeCustomConnectedAccount:
      description: Flipdish Stripe Custom Connected Account associated to the Store
      type: object
      properties:
        StoreId:
          format: int32
          description: Physical Restaurant Id
          type: integer
          example: 500123
        StripeId:
          description: Stripe's own connected account identifier
          type: string
          example: '500123'
        CardPaymentsStatus:
          description: Card payments capability status (Inactive, Pending, Active, Unrequested)
          enum:
          - Inactive
          - Pending
          - Active
          - Unrequested
          type: string
          example: Inactive
        TransfersStatus:
          description: Transfers capability status (Inactive, Pending, Active, Unrequested)
          enum:
          - Inactive
          - Pending
          - Active
          - Unrequested
          type: string
          example: Inactive
        AccountStatus:
          description: Current status of the account
          enum:
          - Disabled
          - Enabled
          - AdditionalInformationRequired
          - PendingVerification
          - Unverified
          - Rejected
          - UpdateExternalAccount
          - PlatformPaused
          type: string
          example: Disabled
    RestApiArrayResult_StripeCustomConnectedAccount_:
      description: Rest api array result
      required:
      - Data
      type: object
      properties:
        Data:
          description: Generic data object.
          type: array
          items:
            $ref: '#/components/schemas/StripeCustomConnectedAccount'
          example: []
    StripeConnectedAccountInfo:
      description: Represents information about a Stripe connected account associated with a bank account
      type: object
      properties:
        AccountStatus:
          description: Stripe connected account status
          enum:
          - Disabled
          - Enabled
          - AdditionalInformationRequired
          - PendingVerification
          - Unverified
          - Rejected
          - UpdateExternalAccount
          - PlatformPaused
          type: string
          example: Disabled
        StripeId:
          description: Stripe connected account id
          type: string
          example: '500123'
        CardPaymentStatus:
          description: Current status of the Card Payment capability of the account
          enum:
          - Inactive
          - Pending
          - Active
          - Unrequested
          type: string
          example: Inactive
        PayoutScheduleInterval:
          description: Payouts Schedule Interval
          enum:
          - Manual
          - Daily
          - Weekly
          - Monthly
          type: string
          example: Manual
        PayoutsEnabled:
          description: Payouts Enabled status
          type: boolean
          nullable: true
          example: true
        PayoutsPaused:
          description: Flag indicating if payouts are paused
          type: boolean
          example: true
        PaymentsEnabled:
          description: Flag indicating if payments are enabled
          type: boolean
          nullable: true
          example: true
    StripeConnectedAccount:
      description: Represents a Stripe custom connected account
      type: object
      properties:
        FlipdishConnectedAccountId:
          format: int32
          description: Flipdish connected account identifier
          type: integer
          example: 500123
        StripeId:
          description: Stripe's own connected account identifier
          type: string
          example: '500123'
        WhitelabelConfigId:
          format: int32
          description: Id of the WhitelabelConfig the connected account is assigned to
          type: integer
          example: 500123
        CardPaymentsStatus:
          description: Card payments capability status (Inactive, Pending, Active, Unrequested)
          enum:
          - Inactive
          - Pending
          - Active
          - Unrequested
          type: string
          example: Inactive
        TransfersStatus:
          description: Transfers capability status (Inactive, Pending, Active, Unrequested)
          enum:
          - Inactive
          - Pending
          - Active
          - Unrequested
          type: string
          example: Inactive
        AccountStatus:
          description: Current status of the account
          enum:
          - Disabled
          - Enabled
          - AdditionalInformationRequired
          - PendingVerification
          - Unverified
          - Rejected
          - UpdateExternalAccount
          - PlatformPaused
          type: string
          example: Disabled
        PayoutsEnabled:
          description: Payouts Enabled status
          type: boolean
          nullable: true
          example: true
        PaymentsEnabled:
          description: Payments Enabled status
          type: boolean
          nullable: true
          example: true
    AccountFieldKeyValuePair:
      description: Represents one populated account field (its key and value)
      type: object
      properties:
        Key:
          description: Depending on the Key, the field's value will be stored in a different field in PayeeBankAccountData
          enum:
          - Iban
          - AccountNumber
          - RoutingNumber
          - BSB
          - BranchCode
          - BankCode
          - InstitutionNumber
          - TransitNumber
          - ClearingCode
          - IfscCode
          - Clabe
          - SortCode
          - Swift
          type: string
          example: Iban
        Value:
          description: The value of the field
          type: string
          example: string
    BankAccountDetail:
      description: ''
      type: object
      properties:
        Id:
          format: int32
          description: Id of this account
          type: integer
          example: 500123
        StoreNames:
          description: Store Names that are attached to this account
          type: array
          items:
            type: string
          example:
          - Example Name
        AccountState:
          description: Status of Account
          enum:
          - Unverified
          - AwatingVerification
          - Verified
          - Grandfathered
          type: string
          example: Unverified
        StripeConnectedAccountInfo:
          $ref: '#/components/schemas/StripeConnectedAccountInfo'
        BankAddress:
          description: Address lf the bank
          type: string
          example: string
        BankCountryCode:
          description: CountryCode of the Bank Account
          type: string
          example: IE
        AccountHolderAddress:
          description: Account Holders Address
          type: string
          example: string
        AccountHolderCountryCode:
          description: Account Holders Country Code
          type: string
          example: IE
        VatNumber:
          description: Account Holders Vat Number
          type: string
          example: string
        CurrencyCode:
          description: Currency of Account
          enum:
          - EUR
          - USD
          - GBP
          - CAD
          - AUD
          - DJF
          - ZAR
          - ETB
          - AED
          - BHD
          - DZD
          - EGP
          - IQD
          - JOD
          - KWD
          - LBP
          - LYD
          - MAD
          - OMR
          - QAR
          - SAR
          - SYP
          - TND
          - YER
          - CLP
          - INR
          - AZN
          - RUB
          - BYN
          - BGN
          - NGN
          - BDT
          - CNY
          - BAM
          - CZK
          - DKK
          - CHF
          - MVR
          - BTN
          - XCD
          - BZD
          - HKD
          - IDR
          - JMD
          - MYR
          - NZD
          - PHP
          - SGD
          - TTD
          - XDR
          - ARS
          - BOB
          - COP
          - CRC
          - CUP
          - DOP
          - GTQ
          - HNL
          - MXN
          - NIO
          - PAB
          - PEN
          - PYG
          - UYU
          - VEF
          - IRR
          - XOF
          - CDF
          - XAF
          - HTG
          - ILS
          - HRK
          - HUF
          - AMD
          - ISK
          - JPY
          - GEL
          - KZT
          - KHR
          - KRW
          - KGS
          - LAK
          - MKD
          - MNT
          - BND
          - MMK
          - NOK
          - NPR
          - PKR
          - PLN
          - AFN
          - BRL
          - MDL
          - RON
          - RWF
          - SEK
          - LKR
          - SOS
          - ALL
          - RSD
          - KES
          - TJS
          - THB
          - ERN
          - TMT
          - BWP
          - TRY
          - UAH
          - UZS
          - VND
          - MOP
          - TWD
          - BMD
          type: string
          example: EUR
        StoreIds:
          description: List of stores to attach to Account
          type: array
          items:
            format: int32
            type: integer
          example:
          - 1
        BankName:
          description: Name of Bank
          type: string
          example: Example Name
        AccountName:
          description: Name of this account
          type: string
          example: Example Name
        Iban:
          description: IBAN of this account
          type: string
          example: string
        Swift:
          description: SWIFT of this bank account
          type: string
          example: string
        NationalClearingCode:
          description: National Clearing Code (BSB in Australia, Routing Number in USA/Canada, NCC in NZ)
          type: string
          example: string
        PopulatedAccountFields:
          description: "A list of one or more populated account fields (field key-value pairs).\r\nIf this list contains at least one item, the Iban, Swift and NationalClearingCode fields will be ignored."
          type: array
          items:
            $ref: '#/components/schemas/AccountFieldKeyValuePair'
          example: []
        RejectionReason:
          description: Reason for Rejection
          type: string
          example: string
        BusinessType:
          description: Business Type
          enum:
          - Individual
          - Company
          - NonProfit
          - GovernmentEntity
          type: string
          nullable: true
          example: Individual
    RestApiResult_ModelBase_:
      description: Rest api result
      required:
      - Data
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/ModelBase'
    ModelBase:
      description: Model base
      type: object
      properties: {}
    FlipdishError:
      type: object
      description: Standard Flipdish API error response. Errors are returned as a JSON object with a human-readable message and a programmatic error code (see https://developers.flipdish.com/docs/error-handling).
      properties:
        error:
          type: object
          description: Error detail object.
          properties:
            errorMessage:
              type: string
              description: Descriptive explanation of the issue.
              example: Invalid or missing parameters.
            errorCode:
              type: string
              description: Unique identifier for programmatic error handling.
              example: BadRequest
            details:
              type: string
              description: Additional context returned in non-production environments.
              example: Validation failed for field 'storeId'.
    RestApiResult_BankAccountDetail_:
      description: Rest api result
      required:
      - Data
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/BankAccountDetail'
    RestApiResult_StripeConnectedAccount_:
      description: Rest api result
      required:
      - Data
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/StripeConnectedAccount'
    StripeAccountLinkRequest:
      description: Represents a request for Stripe account link creation
      type: object
      properties:
        StripeId:
          description: Stripe's own connected account identifier
          type: string
          example: '500123'
        ReturnUrl:
          description: URL to be hit if link creation succeeds
          type: string
          example: https://api.flipdish.co/example
        Collect:
          description: Which information to collect from users at this stage
          enum:
          - CurrentlyDue
          - EventuallyDue
          type: string
          example: CurrentlyDue
        Type:
          description: Either onboarding or edit user information
          enum:
          - Onboarding
          - Update
          type: string
          example: Onboarding
    BankAccountDetailsUpdateRequest:
      description: Represents a request to update bank account information details
      type: object
      properties:
        BankAddress:
          description: Address of the bank account
          type: string
          example: string
        AccountHolderAddress:
          description: Address of the payee
          type: string
          example: string
        VatNumber:
          description: Account Holders Vat Number
          type: string
          example: string
        StoreIds:
          description: List of stores to attach to Account
          type: array
          items:
            format: int32
            type: integer
          example:
          - 1
        BankName:
          description: Name of Bank
          type: string
          example: Example Name
        AccountName:
          description: Name of this account
          type: string
          example: Example Name
        Iban:
          description: IBAN of this account
          type: string
          example: string
        Swift:
          description: SWIFT of this bank account
          type: string
          example: string
        NationalClearingCode:
          description: National Clearing Code (BSB in Australia, Routing Number in USA/Canada, NCC in NZ)
          type: string
          example: string
        PopulatedAccountFields:
          description: "A list of one or more populated account fields (field key-value pairs).\r\nIf this list contains at least one item, the Iban, Swift and NationalClearingCode fields will be ignored."
          type: array
          items:
            $ref: '#/components/schemas/AccountFieldKeyValuePair'
          example: []
        RejectionReason:
          description: Reason for Rejection
          type: string
          example: string
        BusinessType:
          description: Business Type
          enum:
          - Individual
          - Company
          - NonProfit
          - GovernmentEntity
          type: string
          nullable: true
          example: Individual
  securitySchemes:
    oauth2:
      type: oauth2
      description: OAuth 2.0. Implicit grant for first-party portal apps; client credentials grant for server-to-server App Store apps (exchange Client ID + Secret Key for a bearer access token).
      flows:
        implicit:
          authorizationUrl: https://api.flipdish.co/identity/connect/authorize
          scopes:
            api: Access to the Flipdish API
        clientCredentials:
          tokenUrl: https://api.flipdish.co/identity/connect/token
          scopes:
            api: Access to the Flipdish API
